sudo: required
services:
  - docker

before_install:
  - docker build -t nigamshubham14385/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nigamshubham14385/react-test npm test

after_success:
  - docker build -t nigamshubham14385/multi-client ./client
  - docker build -t nigamshubham14385/multi-nginx ./nginx
  - docker build -t nigamshubham14385/multi-server ./server
  - docker build -t nigamshubham14385/multi-worker ./worker
